name: CI/CD Pipeline

# Trigger on pushes and pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job to run tests and build Docker image
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: development
      PYTHONPATH: ${{ github.workspace }}/MessagingService

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: echo "sqlite_db_file=db.sqlite3" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "FLASK_ENV is $FLASK_ENV"
          echo "PYTHONPATH is $PYTHONPATH"

      - name: Print Python path
        run: echo "PYTHONPATH is $PYTHONPATH"

      - name: List all files
        run: ls -R ${GITHUB_WORKSPACE}

      - name: Check Python path
        run: |
          python -c "import sys; print('\n'.join(sys.path))"

      -- name: Print working directory
          run: pwd

      - name: Run tests
        run: pytest tests/

  # Job to build and deploy Docker container
  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./DockerFile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/messagingservice:latest

      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest }}
