name: CI/CD Pipeline

# Trigger on pushes and pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job to run tests and build Docker image
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: development
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: echo "sqlite_db_file=db.sqlite3" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "FLASK_ENV is $FLASK_ENV"
          echo "PYTHONPATH is $PYTHONPATH"

      - name: Run tests
        run: pytest tests/

  # Job to build and deploy Docker container
  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for multiple platforms
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/messagingservice:latest
          platforms: linux/amd64,linux/arm64 # Build for both amd64 and arm64 architectures

      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest }}

  # Job to deploy to GCP Cloud Run
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Add your GCP service account key here

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from DockerHub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/messagingservice:latest

      - name: Tag Docker image for Google cloud run
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/messagingservice:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/messagingservice:latest

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/messagingservice:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/messagingservice:latest \
            --platform managed \
            --region us-west2 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
